### ISSUE TITLE
Seeking approval to make improvements to the plugin

### ISSUE THREAD

**Issue by BelugaWhale** [erversteeg/inventorytotal#4]
Hey @erversteeg,

this is an awesome plugin, thanks for your contribution! There are a few changes I would love to see added:
1. Adding item charge cost tracking to inventory total. (leverage weapon charges plugin or item charges improved)
2. Looting bag tracking
3. Money exp drops to inventory total. (similar to what is in profit tracking)
4. Toggle to change to average per hour total instead. Also a toggle to make it not reset on banking.
5. Fixes for existing bugs found during this process.

Another developer and myself are hoping to make these changes and contribute back to the repo. We thought we would first check with you that you are okay with these changes being added to the plugin, and will merge the PR assuming it meets the quality requirements.

**Comment by erversteeg** [comment]
Hey @BelugaWhale. Sure sounds good
