### ISSUE TITLE
Request To Be Added As a Collaborator

### ISSUE THREAD

**Issue by MosheBenZacharia** [erversteeg/inventorytotal#5]
Hello,

I'm reaching out to ask if you're still maintaining this plugin, I noticed some issues have gone unanswered and I was hoping to add some new functionality.

You can see a WIP of my changes [here](https://github.com/MosheBenZacharia/inventorytotal).

If it's abandoned I'm happy to be added as a collaborator or have ownership transferred.

**Comment by erversteeg** [comment]
Hi Mo. As long as all the changes you make are not on by default, I'm more than happy to merge them into an update.

**Comment by erversteeg** [comment]
Hi Mo. I'd be more than happy to merge and work the changes you've made into an update.

**Comment by MosheBenZacharia** [comment]
You're alive! 

Thanks for replying, although I think at this point the changes are so large they would be better suited for an entirely new plugin rather than try to merge into this one (especially considering the [PR](https://github.com/erversteeg/inventorytotal/pull/3) you just merged will create more merge conflicts than would be feasible to fix).

I also think I've added so much functionality that the plugin has grown to no longer be just 'inventory total', so seems like it would be more clean that way anyways.

All the best!
-Mo

**Comment by erversteeg** [comment]
Nice, good luck with it.
