### ISSUE TITLE
ignore item is not working

### ISSUE THREAD

**Issue by n0coder** [erversteeg/inventorytotal#7]
I installed the plugin to track my inventory
but i have expensive Anchovy pizza in my inventory. I added it to the ignore list box and it did not ignore the pizza.

**Comment by n0coder** [comment]
had to hover over it (applies after banking) i feel like this should be in the title of the feature lol
ignore items: (applies after banking)
/*
Anchovy pizza
*/

**Comment by erversteeg** [comment]
Good idea. I will add it into the title. Eventually I can probably just get it to apply instantly.
