### ISSUE TITLE
Config Toggle for High-Alch values instead og GE

### ISSUE THREAD

**Issue by sololegends** [erversteeg/inventorytotal#9]
Having the ability to show High-Alch data instead of GE value would be wonderful for ironmen and ironwomen who really only have high-alch available.

**Comment by erversteeg** [comment]
This is a great idea. Working on getting this added in.

**Comment by erversteeg** [comment]
Excited to say this feature is now live. I tested it quite a bit but please let me know if there ends up being any issues. Thanks again for the idea this is a great addition.

**Comment by sololegends** [comment]
Woo! Thanks for adding it can't wait to see it in action :D
